apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wuda.componentName" (list . "backend") }}
  labels:
    {{- include "wuda.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_KEY: {{ .Values.secretValues.backend.JWT_KEY | quote }}
  POSTGRES_PASSWORD: {{ .Values.secretValues.db.POSTGRES_PASSWORD | quote }}
