{{- if .Values.db.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wuda.componentName" (list . "db") }}
  labels:
    {{- include "wuda.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secretValues.db.POSTGRES_PASSWORD | quote }}
{{- end }}
