apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wuda.componentName" (list . "frontend") }}
  labels:
    {{- include "wuda.labels" . | nindent 4 }}
data:
  APP_HOST: {{ .Values.frontend.env.APP_HOST | quote }}
  APP_PORT: {{ .Values.frontend.env.APP_PORT | quote }}
  BACKEND_HOSTNAME: {{ include "wuda.backendHostname" . | quote }}
  BACKEND_PORT: {{ .Values.frontend.env.BACKEND_PORT | quote }}
