apiVersion: v1
kind: Service
metadata:
  name: {{ include "wuda.componentName" (list . "frontend") }}
  labels:
    {{- include "wuda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
