apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wuda.componentName" (list . "frontend") }}
  labels:
    {{- include "wuda.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secretValues.frontend.SECRET_KEY | quote }}
