name: Build Backend

on:
  workflow_run:
    workflows: ["Security Scanning", "Linting", "Tests"]
    types:
      - completed
    branches:
      [master, develop]

jobs:
  build-push-backend:
    uses: ./.github/workflows/reusable-build.yml
    # Only run if all prerequisite workflows succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    with:
      service: back-end

