name: CI/CD pipeline

on:
  push:
    branches:
      [ main, develop]
  pull_request:
    branches:
      - main

jobs:
  vulnerability-scan:
    name: source vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: python setup
        uses: actions/setup-python@v6
        with:
          python-version: '3.x' # use latest python 3 version

      # use pip-audit to scan dependencies
      - name: pip-audit install
        run: pip install pip-audit

      - name: back-end audit
        run: pip-audit -r back-end/requirements.txt --desc # add description to output

      - name: front-end audit
        run: pip-audit -r front-end/requirements.txt --desc


      # use bandit to scan source code, output in sarif format
      - name: bandit install
        run: pip install bandit

      - name: back-end bandit
        run: bandit -r back-end/ sarif -o bandit-backend.sarif --exit-zero # exit-zero doesn't fail build, only reports

      - name: upload backend bandit report
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: bandit-backend.sarif
          category: 'bandit backend'

      - name: front-end bandit
        run: bandit -r front-end/ sarif -o bandit-frontend.sarif --exit-zero

      - name : upload frontend bandit report
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: bandit-frontend.sarif
          category: 'bandit frontend'

