name: Linting

on:
  push:
    branches:
      [master, develop]
  pull_request:
    branches:
      [master, develop]

jobs:
  lint-backend:
    uses: ./.github/workflows/reusable-lint.yml
    with:
      service: back-end

  lint-frontend:
    uses: ./.github/workflows/reusable-lint.yml
    with:
      service: front-end

