name: Security Scanning

on:
  push:
    branches:
      [master, develop]
  pull_request:
    branches:
      [master, develop]

jobs:
  scan-backend:
    uses: ./.github/workflows/reusable-security.yml
    with:
      service: back-end

  scan-frontend:
    uses: ./.github/workflows/reusable-security.yml
    with:
      service: front-end

