name: Tests

on:
  push:
    branches:
      [master, develop]
  pull_request:
    branches:
      [master, develop]

jobs:
  test-backend:
    uses: ./.github/workflows/reusable-test.yml
    with:
      service: back-end
    secrets: inherit

  test-frontend:
    uses: ./.github/workflows/reusable-test.yml
    with:
      service: front-end
    secrets: inherit

